lawreto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lawyer.urls')),
    path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lawyer/urls.py
from django.urls import path

from lawyer.views import lawyer_list, lawyer_detail, Home

app_name = 'lawyer'

urlpatterns = [
    path('lawyer', Home, name='homee'),
    path('', lawyer_list, name='lawyer_list'),
    path('<slug:category_slug>/', lawyer_list, name='lawyer_list_by_category'),
    path('<int:id>/<slug:name_slug>/', lawyer_detail, name='lawyer_detail'),
]

lawyer/models.py
from django.db import models
from django.urls import reverse
from accounts.models import Profile
CATEGORY_CHOICES = (
    ('CRIMINAL', 'Criminal'),
    ('EMPLOYMENT', 'Employment'),
    ('CORPORATE', 'Corporate'),)
# Create your models here.


class Category(models.Model):
    profile = models.ForeignKey(Profile, related_name='profile', on_delete=models.CASCADE)
    category_name = models.CharField(max_length=10, db_index=True,choices=CATEGORY_CHOICES)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    city = models.CharField(max_length=20)
#   types = models.CharField(max_length=20)
#   updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('category_name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return reverse('lawyer:lawyer_list_by_category', args=[self.slug])
    # @property
    # def get_lawyer(self):
    #     return Category.objects.filter(categories__category_name=self.category_name)
    def save(self, *args, **kwargs):
        lawyer=Lawyer(*args,**kwargs)
        lawyer.category=self
        lawyer.save()
        super(Category, self).save(*args, **kwargs)

class Lawyer(models.Model):
    category = models.ForeignKey(Category, related_name='lawyer', on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, related_name='profiles', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    charge = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    #city = models.CharField(max_length=200)
    #image = models.ImageField(upload_to='lawyerdp/%Y/%m/%d', blank=True)
    #types = models.CharField(max_length=20)
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)
    # image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    #categ = forms.ModelMultipleChoiceField(queryset=Author.objects.all())
    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('lawyer:lawyer_detail',args=[self.id, self.slug])

    # def save(self, *args, **kwargs):
    #     super(Lawyer, self).save(*args, **kwargs)

lawyer/forms.py
from django import forms
from django.utils.text import slugify

from lawyer.models import Lawyer, Category
CATEGORY_CHOICES = (
    ('CRIMINAL', 'Criminal'),
    ('EMPLOYMENT', 'Employment'),
    ('CORPORATE', 'Corporate'),)


class CategoryForm(forms.ModelForm):
    category_name = forms.CharField(max_length=3,
                                    widget=forms.Select(choices=CATEGORY_CHOICES),)

    class Meta:
        model = Category
        fields = (
            'category_name',
            'city',
        )
    # def __init__(self,profile):
    #     super(CategoryForm, self).__init__()
    #     self.profile=profile


    # def save(self, commit=True):
    #     instancec = super(CategoryForm, self).save(commit=False)
    #     instancec.category_name=self.cleaned_data['category_name']
    #     instancec.city=self.cleaned_data['city']
    #     instancec.slug = slugify(instancec.category_name)
    #     if commit:
    #         instancec.save()

    #     return instancec


class LawyerForm(forms.ModelForm):
    class Meta:
        model = Lawyer
        fields = (
            'name',
            'description',
            'charge',
            'available',
        )

    # def save(self, commit=True):
    #     #instance_1 = super(CategoryForm, self).save(commit=False)
    #     instance = super(LawyerForm, self).save(commit=False)
    #     instance._name=self.cleaned_data['name']
    #     instance._description=self.cleaned_data['description']
    #     instance._charge=self.cleaned_data['charge']
    #     instance._available=self.cleaned_data['available']
    #     instance.slug = slugify(instance.name)
    #     if commit:
    #         instance.save()
    #     return instance

lawyer/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Lawyer
from lawyer.forms import CategoryForm,LawyerForm
from django.contrib.auth.decorators import login_required

@login_required
def Home(request):
    return redirect('lawyer_list')
    # from lawyer.forms import CategoryForm,LawyerForm
    # context = {
    # 'category_form': CategoryForm(),
    # 'lawyer_form': LawyerForm(),
    # }
    # if request.user.profile.role == "LAWYER":
    #     return render(request, 'registration/lawyer_registration.html', context)

    # return redirect('lawyer_list')
def lawyer_save(request):
    if request.method == 'POST':
        cat_form = CategoryForm(request.POST)
        if cat_form.is_valid():
            cat_obj = cat_form.save(commit=False)
            cat_obj.profile = request.user.profile
            cat_obj.save()
            return HttpResponseRedirect('/')

def lawyer_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    lawyers = Lawyer.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        lawyers = Lawyer.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'lawyers': lawyers
    }
    return render(request, 'lawyer/list.html', context)


def lawyer_detail(request, id, slug):
    lawyer = get_object_or_404(Lawyer, id=id, slug=slug, available=True)
    context = {
        'lawyer': lawyer
    }
    return render(request, 'lawyer/detail.html', context)

lawyer/templates/lawyer/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Lawyer{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% include 'lawyer/navbar.html' %}

{% block content %}

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

lawyer/templates/lawyer/detail.html
{% extends 'lawyer/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                <div class="card">
                    <div class="card-body">
                        <div class="col-md-6 text-right">
                            <img src="{% if lawyer.image %} {{ lawyer.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 170px; width: auto">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px">
                            <h3>{{ lawyer.name }}</h3>
                            <h6><a href="{{ lawyer.category.get_absolute_url1 }}">{{ lawyer.category }}</a></h6>
                            <p class="text-muted">Kshs. {{ lawyer.price }}</p>
                            <p>{{ lawyer.description|safe|linebreaksbr }}</p>
                        </div>
                    </div>
                </div>
              </div>


          </div><!-- /.blog-post

        </div><!-- /.blog-main -->
      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %} -->

lawyer/templates/lawyer/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    {% if category %}{{ category.categoryname }} {% else %} Lawyers {% endif %}
{% endblock %}

{% block content %}
   <div class="container-fluid">
<div class="row" style="margin-top: 6%">

<div class="col-sm-8 blog-main">

  <div class="blog-post">
	  <div class="row">
	  {% for lawyer in lawyers %}
	      <div class="col-md-4">
	        <div class="thumbnail">
            <a href="{{ lawyer.get_absolute_url }}">
                <img src="{% if lawyer.image %} {{ lawyer.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
            </a>
            <div class="caption">
            <h3 class="text-center">
                <a href="{{ lawyer.get_absolute_url }}">{{ lawyer.name }}</a>
            </h3>
            <p class="text-center">Kshs. {{ lawyer.price }}</p>
        </div>
	    </div>
	    </div>
	  {% endfor %}
	  </div>


  </div><!-- /.blog-post -->

</div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module">
            <h4>Categories</h4>
            <ol class="list-unstyled">
              <li {% if not category %} class="active"{% endif %}><a href="{% url 'lawyer:lawyer_list' %}">All</a></li>
            {% for c in categories %}

              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.category_name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

lawyer/templates/lawyer/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #5AC8FA;">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
      <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'lawyer:lawyer_list' %}" style="color: #ffffff">Henrylab Network</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
          {% if request.user.is_authenticated %}
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'logout' %}">logout</a></li>
            {% else %}
          <li class="divider"></li>
          <li><a href="#" style="color: #ffffff">Sign in</a></li>
         <li><a href="#" style="color: #ffffff">Sign up</a></li>
        </ul>
         {% endif %}
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>